### ISSUE TITLE
Unbind without disconnect for pooled connection

### ISSUE THREAD

**Issue by vgionco** [pingidentity/ldapsdk#105]
Hello,
I can't find a way, on a pooled connection, to send an Unbind request without closing the connection. The best workaround I can find is using releaseAndReAuthenticateConnection(conn), but this performs an extra anonymous Bind request I'd want to avoid.
For example (catch{} block omitted):

```
        LDAPConnection conn = null;
        try {
            conn = pool.getConnection();
            BindResult res = conn.bind(userDN, userPassword);
            ResultCode resultCode = res.getResultCode();
            // ... do something with result
            
            // Here I just want to unbind the connection before releasing it; I'd like to just do something similar to:
            //       pool.unbindConnection(conn);
            // or 
            //       pool.releaseAndDeauthenticateConnection(conn);
            //       conn = null;
            // 
            // but I have to do this one, instead:
            pool.releaseAndReAuthenticateConnection(conn);
            conn = null;
        } finally {
            if (conn != null) {
                pool.releaseConnection(conn);
            }
        }
```
Is there any method to do that?
Thanks in advance.

**Comment by dirmgr** [comment]
Although it is very unfortunately named, an unbind request isn't the opposite of a bind request. That is, it doesn't revert a connection to an unauthenticated state. Instead, an unbind request is a signal to the directory server that the client is going to close the connection. If the client doesn't close the connection, then the server will. There is no way to continue using a connection after sending an unbind request.

If you want to change the authentication state on a connection, then the correct way to do that is by sending another bind request on the same connection. If that bind request is an anonymous simple bind (that is, a simple bind request in which both the DN and password are null or empty), then the connection will be reverted to an unauthenticated state.

If you want connections in your connection pool to be unauthenticated, then the best way to accomplish that would be to create the pool with an anonymous simple bind request. Then, when you call pool.releaseAndReAuthenticateConnection, the LDAP SDK will re-bind with that anonymous simple bind request and revert the connection to an unauthenticated state.

Also note, that instead of you checking out the connection, processing an operation on it, and releasing the connection back to the pool, you should instead let the connection pool do all of the connection management for you. That would be more convenient (because you only need to make one call rather than several with a try-catch block) and more reliable (because the code you have doesn't do any error checking, so the connection you're releasing back to the pool after an exception might not be valid anymore), and you could also take advantage of other features like the ability to automatically re-try the operation on a newly-established connection if the LDAP SDK detects that a failed attempt was because the connection it had tried to use wasn't valid anymore. In that case, you would just use pool.bindAndRevertAuthentication(userDN, userPassword), and if the pool was created with an anonymous simple bind request, then the connection would automatically be reverted to an unauthenticated state after processing the bind operation as the specified user.

**Comment by vgionco** [comment]
I see. Thanks for the explanation (and, more in general, for that great project).
