### ISSUE TITLE
Reading LDIF records with "control" RDNs

### ISSUE THREAD

**Issue by david0** [pingidentity/ldapsdk#112]
Unfortunately our database has entries where the rdn attribute is `control`: 

```
dn: control=sdf,dsaId=1,dc=root
control: sdf
objectClass: sdfControl
linkUnavailThresh: 10
```

We are reading all files as changetypes with defaultAdd=true, since we have both.
For this special case its ends up with a control `sdf` instead as an attribute, which leads to wrong diffs being generated.

We do not have any LDIF files with real controls in it, so it would also be ok to disable this feature completely.

Is there some way you could improve that? Otherwise we have to somehow figure out before parsing if its an ldapadd or ldapmodify style file.

Test:

```java
	@Test
	public void readControlRecord() throws LDIFException {
		LDIFChangeRecord record = LDIFReader.decodeChangeRecord(true,
				"dn: control=A,dc=root",
				"control: A",
				"objectClass: class1",
				"a: a1");

		assertTrue(((LDIFAddChangeRecord) record).getEntryToAdd().hasAttribute("control"));
		assertTrue(record.getControls().isEmpty());
	}
```

**Comment by dirmgr** [comment]
This is a problem that results from a combination of two issues:

* The control attribute immediately follows the DN. If it were later in the set of attributes, it wouldn't be an issue.
* You're using either the readChangeRecord or readLDIFRecord methods. If you knew that it was an entry, then readEntry wouldn't have this problem.

The LDIF specification (RFC 2849) states that LDIF change records may include zero or more LDAP controls between the DN and the changetype. Control records start with "control:" and are followed by at least the OID, and optionally a criticality and/or value. When the LDIF reader is parsing a change record or a generic LDIF record that may be an entry or a change record, if it sees "control:" immediately following the DN, then it will try to treat it as a change record with one or more LDAP controls.

In the current version of the LDAP SDK, there are three things that you could do to work around this behavior:

* You can re-order your entries so that the control attribute doesn't come first.
* You can add "changetype: add" immediately after the DN for all records that don't currently have a changetype.
* You could have separate files for entries and change records. You could read the entries with readEntry and read the change records with readChangeRecord.

However, I did go ahead and commit a change to the LDAP SDK that can allow you to work around this, as long as you don't have any change records that include LDAP controls. I've added a new LDIFReader.setSupportControls method that can be used to disable its support for LDAP controls. If you call that method with an argument of true, then it will treat a line that starts with "control:" and immediately follows the DN as a line that specifies an attribute named "control:". It will either read it as an entry (if you're using readLDIFRecord) or as an add change record (if you're using readChangeRecord with defaultAdd set to true; if you use readChangeRecord with defaultAdd set to false, then it will reject the record because of the missing changetype).

Again, the change to the LDAP SDK only works if you don't need to support change records with LDAP controls. If you need to support a mix of entries and change records, and if you need to support change records with LDAP controls, then you'll have to use one of the workarounds I outlined above.

This change will be included in the next release of the LDAP SDK, and that happens to be pretty imminent, so you shouldn't need to wait long to get it.

**Comment by david0** [comment]
Thanks again for that change and the hints! Good idea with the re-ordering.

I'll use setSupportedControls for the moment. Maybe we can change all datasources to include changetype in future, but it would take time.
