### ISSUE TITLE
What is the proper way to make a search call in async mode?

### ISSUE THREAD

**Issue by gredwhite** [pingidentity/ldapsdk#171]
Based on  https://docs.ldap.com/ldap-sdk/docs/getting-started/asynchronous.html

I try to implement a function which will return entry by DN in async manner. So my code is:

 ```
       val searchRequest = SearchRequest(
            EmptyAsyncListener(),
            dn,
            SearchScope.BASE,
            DereferencePolicy.NEVER,
            1,
            0,
            false,
            Filter.createPresenceFilter("objectClass"),
            *attributes,
        )
        val asyncRequestId = getConnection().asyncSearch(searchRequest)
        val ldapResult = asyncRequestId.get()
```

But at this case I see that `ldapResult ` has a type `SearchResult` but I expect to have a `SearchResultEntry` (or collection of `SearchResultEntry`)

![image](https://github.com/user-attachments/assets/7324d8eb-c0c3-4d82-9b34-4d84e7929b4c)

Eventually I was able to imlement working example using concurrent primitives from java.util.concurrent:

```
        val latch = CountDownLatch(1)
        val ref = AtomicReference<SearchResultEntry>()
        val searchRequest = SearchRequest(
            SimpleAsyncListener(latch, ref),
            dn,
            SearchScope.BASE,
            DereferencePolicy.NEVER,
            1,
            0,
            false,
            Filter.createPresenceFilter("objectClass"),
            *attributes,
        )
        getConnection().asyncSearch(searchRequest)
        latch.await()
        val entry = ref.get()
```
listener implementation:

```
class SimpleAsyncListener(private val latch: CountDownLatch, private val ref: AtomicReference<SearchResultEntry>) :
    AsyncSearchResultListener {


    override fun searchEntryReturned(@NotNull searchEntry: SearchResultEntry) {
        ref.set(searchEntry)
        latch.countDown()
    }


    override fun searchReferenceReturned(
        @NotNull searchReference: SearchResultReference
    ) {
        // No implementation required.
    }

    override fun searchResultReceived(
        @NotNull requestID: AsyncRequestID,
        @NotNull searchResult: SearchResult
    ) {

    }
}
```

It works but I am afraid that it is an overengeeniring. Is there way to achieve the same result in a simpler way ?

**P.S.** Example is artificial just to investigate async API

**Comment by dirmgr** [comment]
No, you're doing it the right way. A search can return multiple matching entries, so you need to use the listener to handle them as they are returned. There are two basic ways to accomplish this:

* Simply collect the results as you have done and then access them once the search has completed. Note that the LDAP SDK already provides a BasicAsyncSearchResultListener class that does this, so you don't really need to create your own implementation if it does what you need.

* Have the listener act on the matching entries as they are returned.

The best approach to take really depends on what you're trying to do with the search and its results.

**Comment by gredwhite** [comment]
Well, got it. 

How can I be sure that no more result will be returned ?

**Comment by dirmgr** [comment]
When asyncRequestId.get() returns, then all of the results will have been returned. Alternatively, the AsyncSearchResultListener.searchResultReceived method can also be used to indicate that.

LDAP doesn't really provide a mechanism to retrieve multiple entries by DN, so you'll need a separate search request for each of them. Each of those search operations should have a separate listener instance for each of them because BasicAsyncSearchResultListener is not threadsafe. Since each of your searches will return at most one entry, then it's fine to use BasicAsyncSearchResultListener.

The guidance around not using it for searches that return a large number of entries is primarily based on the potential for consuming a large amount of memory. If you have a server with hundreds of millions of entries, and a search that tries to retrieve all of them, then the listener would try to hold all of them, and that could result in out of memory errors.

**Comment by gredwhite** [comment]
> LDAP doesn't really provide a mechanism to retrieve multiple entries by DN, so you'll need a separate search request for each of them.

What about using single request with OR filter ?

**Comment by dirmgr** [comment]
An OR filter could work if there were a way to identify all of the desired entries with that filter. However, since you indicate that you want to retrieve the entries by DN, and since I believe that we previously established that Active Directory doesn't support the entryDN operational attribute, then I don't believe that there is any way to craft an OR filter that will allow you to retrieve multiple entries based on their DN from Active Directory.

**Comment by gredwhite** [comment]
> An OR filter could work if there were a way to identify all of the desired entries with that filter. However, since you indicate that you want to retrieve the entries by DN, and since I believe that we previously established that Active Directory doesn't support the entryDN operational attribute, then I don't believe that there is any way to craft an OR filter that will allow you to retrieve multiple entries based on their DN from Active Directory.

Actually not. I have a function that creates a filter for multiple DNs

```
val dns: List<String> = ...
Filter.createORFilter(
      dns.map {
           Filter.createEqualityFilter("distinguishedName", it)
     }

```)

**Comment by dirmgr** [comment]
If that filter works and you want to use it, then that is an option. I'm not going to provide guidance as to the best way to interact with any specific type of directory server, and especially not for servers that I'm unfamiliar with and do things in nonstandard ways.
