### ISSUE TITLE
Missing UnboundID LDAP SDK Free Use License terms in the *.properties files header

### ISSUE THREAD

**Issue by SzymonKowalczyk** [pingidentity/ldapsdk#27]
As the readme.txt states: 

```
It is also available under the non-open source UnboundID LDAP SDK Free Use
License, which allows the LDAP SDK to be freely used in free or commercial
applications as long as the LDAP SDK itself is not altered.
```

Unfortunately for my purposes there are some files (mosty *properties) where the header contain different license terms.

f.e.:

https://github.com/pingidentity/ldapsdk/blob/master/messages/unboundid-ldapsdk-args.properties

```
# Copyright 2008-2017 UnboundID Corp.
# All Rights Reserved.


# Copyright (C) 2008-2017 UnboundID Corp.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License (GPLv2 only)
# or the terms of the GNU Lesser General Public License (LGPLv2.1 only)
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses>.
```

There is no info about non-opensource licence.

Incomplete terms goes into the jar. License code scan for may organization forbid me to use yours library because of that.

**Comment by dirmgr** [comment]
Those are copyright headers. We use those copyright headers everywhere in the project, including for all Java source, properties files, shell scripts, batch files, XML files, etc., which we consider to be the “source code” for the LDAP SDK. The GPLv2 and LGPLv2.1 are source code licenses that depend on copyright (although they sometimes call it “copyleft”, since it works differently than most copyright notices in that they grant you rights rather than restrict them) to specify what you can do with the code, and also with binaries (like classes and jar files) built from that code. The GPL and LGPL licenses specifically recommend putting those notices in every source file.

The UnboundID LDAP SDK Free Use License isn’t a source license. It doesn’t grant you any special rights to the source code, but just to the jar file that we provide. It says that you can use and redistribute it for free in open source and proprietary software as long as you don’t alter the LDAP SDK itself. It covers the resulting project as a whole, so there’s not really any need to include a separate notice in each source file.

We previously didn’t include a copy of the complete license text in the jar file, but I have just committed a change that ensures they are included. So they’ll be included in the jar file starting in the next release (which will be 4.0.0, although I’m not exactly sure when that will be). If you need it before then, you can check out and build the LDAP SDK for yourself.

Further, if you use Maven for your project’s dependencies, the POM that we use for the Central Repository includes all three licenses.

**Comment by SzymonKowalczyk** [comment]
Thank you very much for quick response.

The license file in the jar is the perfect solution in my case.
