### ISSUE TITLE
Cannot mock LDAPConnection for testing

### ISSUE THREAD

**Issue by jasonj-wheeler** [pingidentity/ldapsdk#29]
Since LDAPConnection is marked final, it cannot be mocked for testing purposes. Additionally, LDAPInterface which LDAPConnection implements does not include the ```public ExtendedResult processExtendedOperation(final ExtendedRequest extendedRequest)``` method, so it also cannot be used.

Can you either remove the final declaration from LDAPConnection or add the processExtendedOperation() methods to the LDAPInterface?

I can submit a PR if you'd like.

**Comment by dirmgr** [comment]
Thanks for your interest in the LDAP SDK. Unfortunately (at least from your perspective), both of these are intentional.

All classes in the LDAP SDK except those explicitly intended to be subclassed are declared final. This is a good programming practice for a number of reasons, including performance (there are a number of optimizations that can be employed for final classes that can’t be employed for non-final classes) and reliability (ensuring that third-party code doesn’t overload a method in a way that introduces incompatibility or violates an assumption). It also helps ensure that the API remains stable, which is something that we are extremely committed to maintaining, so that code written with an earlier version of the LDAP SDK will continue working, without the need for alteration or even recompilation, against a later version.

I should point out that there are also a number of non-final classes in the LDAP SDK that are only intended to be extended by code that is internal to the LDAP SDK itself and not by third-party code. As such, each interface and non-final class in the LDAP SDK is marked with either the `@Extensible` or `@NotExtensible` annotation type. Third-party developers are free to inherit from classes and interfaces that are marked with `@Extensible`, but we do not support third-party implementations of classes that are marked `@NotExtensible`. We guarantee the stability of the API so that third-party code can make calls into existing public methods in classes that are marked `@NotExtensible`, but we do not guarantee that we won’t introduce additional abstract methods, which would break third-party implementations.

`LDAPInterface` is one of those interfaces that is marked `@NotExtensible`, and we therefore do not support third-party implementations of it. We have introduced new methods into this interface in the past, and we may do so in the future. However, we have intentionally omitted methods for certain types of operations, including abandon, bind, unbind, and extended operations. The reason for this is that these types of operations may not always be applicable in all contexts where `LDAPInterface` may be used now or in the future. For example, we’re considering adding an `LDAPInterface` implementation that interacts with data in an LDIF file as if it were data stored in an LDAP directory, and extended operations don’t make sense in that context. Further, certain types of operations may have unexpected consequences for `LDAPInterface` implementations that aren’t simple connections. For example, performing a bind operation or a StartTLS extended operation against a connection pool isn’t something that should be done lightly because it could impact the behavior of subsequent operations processed in that pool.

Compatibility with mock testing frameworks is not currently a priority for the LDAP SDK. However, testability is something that we do value, and the LDAP SDK does provide several features to help with that. In particular, the `com.unboundid.util.LDAPTestUtils` class provides a number of convenience methods for testing frameworks, and the in-memory directory server (and the broader `LDAPListener` API that the in-memory directory server uses) provides a great deal of flexibility for processing operations with the existing LDAP SDK code and getting exactly the behavior that you want.

For example, it sounds like you want to perform testing with extended operations. Rather than overriding a connection’s `processExtendedOperation` method, you could easily create an in-memory directory server instance, establish a connection to that instance, and send the desired request to that instance. This is a very lightweight thing to do, and you can get a great deal of control over how you want the in-memory directory server to behave using an `InMemoryOperationInterceptor`. This API allows you to intercept and alter the request before the server processes it, alter the server’s response before it gets sent back, or forego the server’s processing altogether and just return an arbitrary result that you define. I’d expect that this doesn’t require substantially more effort than you would need to use for mocking purposes, and you don’t have to worry about whether there might be any unexpected consequences from bypassing LDAP SDK code that isn’t meant to be bypassed.

Alternately, since we’re talking about extended operations in particular, you could create your own `InMemoryExtendedOperationHandler` to perform whatever processing you want for a particular type of extended request. While that is a lot more powerful, it’s also significantly more advanced than going with an interceptor if you’re just looking to do something like return a predefined response.

But if you still want to go with a mock-based approach, then there are mocking frameworks that allow you to mock final classes. A quick Google search shows that both Mockito 2.x and PowerMock provide support for mocking final classes, and there may be others.

**Comment by jasonj-wheeler** [comment]
Thank you for the detailed response. I will take a look at some of the suggestions you propose--the in-memory directory server seems like it could be a good fit for my use case. Thank you.

**Comment by jasonj-wheeler** [comment]
As a follow up, and for your information, I did investigate some of your suggestions including the in-memory database but in the end we went with another library because the inability to easily mock those classes became too much of a blocker.

**Comment by david0** [comment]
I have exactly the same issue than @jasonj-wheeler.

I like would re-raise this question in the light of JVM enhancements.
As far as I know, even non final classes are inlined at latest by JIC.
Adding new methods to the LDAPInterface class has become easier with default methods in Java 8.

For me its totally ok if these classes are marked with `@NotExtensible` and I have more maintainance effort when I mock these classes. 
The disadvantages by using final here are far bigger to me than the flexibity gained by a technical enforcement of something that"s anyway documented.

You can mock final methods, but its slow. The InMemoryDatabaseServer is nice, but I find it still bulky if I just want to write a simple unit test.

**Comment by dirmgr** [comment]
I really don't want to make LDAPConnection non-final. However, I have made a couple of changes to help make it easier to mock:

* I created a FullLDAPInterface interface that extends LDAPInterface and adds support for a few additional methods, including close, bind, and processExtendedOperation. LDAPConnection, AbstractConnectionPool, and InMemoryDirectoryServer have been updated to implement this interface rather than just LDAPInterface. I expect that in the vast majority of cases where you reference LDAPConnection, you can now use FullLDAPInterface instead.

* I created a non-final MockableLDAPConnection class that implements FullLDAPInterface and wraps an LDAPConnection. All of the methods in that class delegate to the corresponding methods in LDAPConnection by default, but you can override any of them to implement the desired behavior for mocking purposes. If your test code uses FullLDAPInterface (or just LDAPInterface) instead of LDAPConnection, then you should be able to use a MockableLDAPConnection subclass in most cases.

**Comment by david0** [comment]
Thank you, nice to see some improvements here!

Unfortunately we are using `LDAPConnection.processOperation` to execute requests that have been calculated by diffing two trees. We are also executing some extended requests via `ExtendedRequest.process(LDAPConnection, int)` too, but I guess these could be changed to use `FullLDAPInterface.processExtendedOperation`.

I will have to give it a try later, maybe next week I will manage to do it.

**Comment by david0** [comment]
Finally I managed to try it a little more. Still I'm not able to mock using `MockableLDAPConnection` :-(

1. Is it possible to add `processOperation(LDAPRequest)` to `FullLDAPInterface`?
2. We are using `connectionPool.releaseConnection(connection)`. I can add an `if(connection instanceof LDAPConnection)` before that to skip that during unit testing, but its not the nicest thing to do just to enable unit testing
