### ISSUE TITLE
How to support Chinese characters in search base

### ISSUE THREAD

**Issue by rickywu** [pingidentity/ldapsdk#38]
realm.ldap.accountBase = OU=用户,DC=abc,DC=com

if search base include Chinese characters will cause this error

> LDAPSearchException(resultCode=32 (no such object), numEntries=0, numReferences=0, errorMessage='0000208D: NameErr: DSID-03100238, problem 2001 (NO_OBJECT), data 0, best match of:

remove OU=用户 works fine.

**Comment by dirmgr** [comment]
In general, LDAP strings should be encoded as UTF-8, and the LDAP SDK will automatically use the UTF-8 encoding when encoding strings for use in a request.

However, if you're reading the value from a properties file, it might be that the encoding used when writing the properties file doesn't match the encoding that is being used when reading the properties file. The InputStreamReader class allows you to specify the character to use when reading strings from a file.

Another, and probably more foolproof, way to avoid this problem is to escape any non-ASCII characters so that the string that the encoding isn't an issue. I believe that the correct escaped representation of the DN you have above is "OU=\e7\94\a8\e6\88\b7,DC=abc,DC=com".

**Comment by rickywu** [comment]
I checked the properties file encoding is utf-8, I'll check with the GitBlit team.
