### ISSUE TITLE
DN.toMinimallyEncodedString adds a \

### ISSUE THREAD

**Issue by surendarchandra** [pingidentity/ldapsdk#54]
Minor issue: 
_new DN("<GUID=f3ddad46-4332-4871-ae1a-92aa29b0887f>").toMinimallyEncodedString_
gives me _"<GUID=f3ddad46-4332-4871-ae1a-92aa29b0887f\>"_

while _new DN("<GUID=f3ddad46-4332-4871-ae1a-92aa29b0887f>").toString_
gives me _"<GUID=f3ddad46-4332-4871-ae1a-92aa29b0887f>"_

Note the \ before > in the end.

**Comment by dirmgr** [comment]
This is not a bug in the LDAP SDK. Or if there is a bug, then it’s not what you think it is.

The only potential bug here is that the LDAP SDK isn’t rejecting the string “`<GUID=f3ddad46-4332-4871-ae1a-92aa29b0887f>`” because it is not a valid DN. That’s because “`<GUID`” isn’t a valid attribute name because the less-than character is not an allowed character.

However, the LDAP SDK is being lenient with what it accepts in this case, so it’s trying to work with what you gave it. Therefore, it ignores the fact that “`<GUID`” isn’t a valid attribute name and it tries to use “`f3ddad46-4332-4871-ae1a-92aa29b0887f>`” as the attribute value. But technically, that’s not valid either because RFC 4514 (https://docs.ldap.com/specs/rfc4514.txt) section 2.4 states that in the string representation of a DN, any occurrence of the greater-than character must be escaped as either “`\>`” or “`\3e`”.

So the `DN.toMinimallyEncodedString` method is doing the right thing because it’s ensuring that the “`>`” character gets properly escaped as “`\>`”. That doesn’t happen when you just use `DN.toString` because if you create a DN from a string, `DN.toString` just returns the string that you used to create the DN.

**Comment by surendarchandra** [comment]
Thanks @dirmgr. I was surprised that <GUID=... was deemed a valid DN (expected it to fail). I am using DN code as a syntax validator for user specified DNs. Similarly, (GUID=f3ddad46-4332-4871-ae1a-92aa29b0887f) also works though not sure if it is correct. 

Specifying <GUID=... is a Microsoft supported "DN" for ActiveDirectory. Was hoping to avoid special casing AD, for now will use toString!! Thanks much

**Comment by surendarchandra** [comment]
Awesome, looking forward to the new code. I could definitely use a strict validator.

Agreed with ActiveDirectory; not sure why they "innovate" in these weird ways.
