### ISSUE TITLE
schema.getAttributeType returns null for attributes without a description

### ISSUE THREAD

**Issue by teppos** [pingidentity/ldapsdk#55]
If you have the following (simplified) schema
```
dn: cn=schema
attributeTypes: ( 1.1 NAME 'test1' DESC 'test1' EQUALITY caseIgnoreMatch SYNTAX 1.1.1 SINGLE-VALUE )
attributeTypes: ( 1.2 NAME 'test2' DESC '' EQUALITY caseIgnoreMatch SYNTAX 1.1.1 SINGLE-VALUE )
```

and try to get AttributeDefinition for the attributes:
- `schema.getAttributeType("test1")` returns the expected result 

**but**

- `schema.getAttributeType("test2")` will return **null**

**Comment by dirmgr** [comment]
The problem that you’re running into is that an empty description is not valid. Therefore, the LDAP SDK isn’t able to parse the attribute type definition with the empty description, and so it’s not showing up in the schema.

[RFC 4512](https://docs.ldap.com/specs/rfc4512.txt) section 4.1.2 defines the string representation of an attribute type definition, and it states that the `DESC` element has a type of `qdstring`. The `qdstring` type is defined in section 4.1 of the same document as a `dstring` surrounded by single quotes, and it defines a `dstring` as one or more UTF-8 characters, but with the single quote and backslash characters escaped by a backslash.

In fact, if you try to create an attribute type definition with that string representation (using the `AttributeTypeDefinition(String)` constructor), the LDAP SDK will throw an `LDAPException` with a result code of “decoding error” and a message of “Unable to parse string '( 1.2 NAME 'test2' DESC '' EQUALITY caseIgnoreMatch SYNTAX 1.1.1 SINGLE-VALUE )' as a schema element because it contained an empty quoted string.”.

This is perhaps easy to overlook when you’re creating a schema from one or more entries because the LDAP SDK has methods for parsing schema that silently swallow any parsing errors. However, it also provides methods for not hiding those errors. For example, instead of using the constructor that just takes an Entry, you could use the constructor that takes an Entry and a bunch of String->LDAPException maps that will be updated with information about any unparsable elements that are found in the provided entry. Similarly, if you’re loading schema from one or more files, there’s a `Schema.getSchema` method that takes a list of schema files and a boolean argument that indicates whether to throw an exception on an unparsable element.

**Comment by teppos** [comment]
Ok, thank you for the error description. 
Actually I read the Schema from a file (using getSchema(java.io.InputStream inputStream)) so I didn't notice any exceptions from it.

I have modified the Schema i was working with to have descriptions and it solved my issue. 

Thank you for your help.

**Comment by dirmgr** [comment]
Glad you got it working. FYI, you can also just leave the DESC field out of the definition altogether if you don't need a description.
