### ISSUE TITLE
LDAPException(resultCode=4 (size limit exceeded), numEntries=1000, numReferences=3, errorMessage='size limit exceeded', ldapSDKVersion=4.0.10,

### ISSUE THREAD

**Issue by HelloNanKe** [pingidentity/ldapsdk#65]
When i use ldap-sdk imprt user from the AD,i got the exception:
```
LDAPException(resultCode=4 (size limit exceeded), numEntries=1000, numReferences=3, errorMessage='size limit exceeded', ldapSDKVersion=4.0.10, revision=b2272901fd62ad978017ff1aeb049cafc1999b12')
	at com.unboundid.ldap.sdk.LDAPConnection.search(LDAPConnection.java:3773)

```
I tried:
```
  SearchRequest searchRequest = new SearchRequest(rootDc, SearchScope.SUB, resFilter, (String[]) adKeys.toArray(new String[0]));
        searchRequest.setSizeLimit(10000);
       //searchRequest.setSizeLimit(0);
      //searchRequest.setSizeLimit(-1);
```
but it not works for me.
Our ad have more than 5000 user's;
Is there any other solution here?

**Comment by dirmgr** [comment]
The "size limit exceeded" result indicates that the number of entries matching the search criteria is more than the maximum that can be returned for a single search operation. Even though the request from the client includes a size limit element, the server often imposes its own size limit as well, and that's almost certainly what you're running into in this case. It looks like AD is configured to not allow you to retrieve more than 1000 entries from a single search.

There are a couple of ways that you can deal with this. The best solution is to use the [simple paged results control](https://docs.ldap.com/ldap-sdk/docs/javadoc/index.html?com/unboundid/ldap/sdk/controls/SimplePagedResultsControl.html) to break the search up into multiple pages of results. I'm not really familiar with Active Directory, but a quick search seems to suggest that it does support this control.

If the simple paged results control isn't an option for some reason, then your other options are:

* There is an alternative to the simple paged results control called the [virtual list view (VLV) request control](https://docs.ldap.com/ldap-sdk/docs/javadoc/index.html?com/unboundid/ldap/sdk/controls/VirtualListViewRequestControl.html). This is similar in that it can allow you to retrieve your results in pages rather than all at once, but it can be more expensive to use because it also requires the results to be sorted. Again, I'm not very familiar with AD, but it does sound like it might also support this control.
* See if you can reconfigure the server to raise the limit on the number of entries that can be returned, whether globally or for the account that you're using.
* See if you can find a way to adjust your filter so that it only matches a range of the entries, and then issue the search for different ranges. For example, instead of a filter like "(objectClass=*)", maybe you could use "(cn=a*)" to get all the entries with cn values starting with the letter "a", or "(cn<=e)" to get all the entries with cn values that are less than or equal to "e". This isn't a great option, especially if you have a huge data set, but it might be workable for a directory as small as yours is.

**Comment by HelloNanKe** [comment]
I've tried many methods. I've found there is one way to solve my problem. 
```
SearchRequest searchRequest = new SearchRequest(rootDc, SearchScope.SUB, resFilter, (String[]) adKeys.toArray(new String[0]));
        searchRequest.setControls(new SimplePagedResultsControl(50000, null));
        //0代表不限制
        searchRequest.setSizeLimit(100000);
```
The situation we use AD is to export the user to database.Update based on timestamp increment.
