### ISSUE TITLE
LDAP error code 81 while using LDAPS connection

### ISSUE THREAD

**Issue by Fourfour06** [pingidentity/ldapsdk#69]
Hello,

I'm having a similar issue as what is reported here:
https://github.com/pingidentity/ldapsdk/issues/62

I'm trying to establish a LDAPS connection using the constructor doing sequentially both "connect" and "bind" but it results in getting a LDAP error code 81. I'm using our own specific socket factory for that which we know use to work in version 4.0.6.

After having upgraded to 4.0.11, we're now getting these errors code 81 (server down).

Here is the failing code I use to create the connection (I know it's not much):

```
connection= new LDAPConnection( socketFactory,
                                connectionOptions,
                                host,
                                pPort,
                                pBindDN,
                                pPassword );
```

As I said, this code was working correctly in 4.0.6, but not in 4.0.11.

After multiple tries, I found this (not so great) workaround:

```
connection= new LDAPConnection( socketFactory,
                                connectionOptions,
                                host,
                                pPort );


Thread.sleep( 250 );

connection.bind( pBindDN, pPassword );
```
We're using Java 8 Corretto JVM (the reason why we upgraded to 4.0.11 is because Amazon wasn't part of the recognized JVM vendor's list in LDAPConnections#DEFAULT_ALLOW_CONCURRENT_SOCKET_FACTORY_USE parameter).

Maybe I'm not doing things the right way.
Do you have any clue about what's going wrong here?

Any help would be appreciated, thanks in advance.

**Comment by dirmgr** [comment]
I've just done some testing with the Coretto JVM and thus far am unable to reproduce any problems with it. I used the attached [TLSConnectAndBindTest.java.txt](https://github.com/pingidentity/ldapsdk/files/3457953/TLSConnectAndBindTest.java.txt) program (note that I had to add a ".txt" extension since GitHub wouldn't allow me to attach a ".java" file) to test both with the LDAP SDK's in-memory directory server and with an external instance of the Ping Identity Directory Server, and have not encountered any problems. Can you confirm whether this program reproduces the problem in your environment?

Given that it sounds like the problem goes away if you insert a delay between establishing the connection and attempting the bind, I wonder if the change made in revision 9a19a281039942e79cc994d14923f3cedd6106b0 (included in the 4.0.10 release) might be to blame. This is a very simple change that merely starts TLS negotiation on a connection as soon as it's established rather than waiting until the first attempt to communicate on the connection as was previously the case. There shouldn't be any adverse effect as a result of this, and this was already the case for connections secured with the StartTLS extended operation, but it's the only thing that I can think of that might be responsible.

At any rate, the best thing to do would probably be to try reproducing the problem with the JVM's TLS debugging enabled. You can do that by launching the JVM with "-Djavax.net.debug=all". That should provide a lot more information about the attempted TLS negotiation, and could help us figure out what's going wrong.

**Comment by Fourfour06** [comment]
Thanks for the quick answer.

Here are the traces with the JVM option you've indicated: [ErrorCode81.txt](https://github.com/pingidentity/ldapsdk/files/3460650/ErrorCode81.txt)

Hope it could help understand the issue.

Thanks for the test class too. I'll try to check if I can manage to use it, but it can be challenging because we're unable to reproduce this issue in an other environment than our test environment (which does it always) and those are on an independant network that we can't easily access from our development network, but that's our problem to deal with.

**Comment by dirmgr** [comment]
I would have expected more debug output. This looks like it's from the very end of the TLS negotiation process, right when it fails. It would be helpful to see what led up to it.

However, as far as I can tell, it looks like the failure is in some way related to TLS renegotiation. The "waiting for close_notify or alert" indicates that the connection already considers itself closed, and it's just waiting for either the socket to be closed or an SSL alert message with additional information, and the "state 3" indicates that it's in the process of attempting to renegotiate the session.

Immediately after that, you can see that it reads data, but it's not able to interpret it, and that leads to the "fatal, unexpected_message". It follows that by invalidating two existing TLS sessions, closing the connection, and throwing the exception that the LDAP SDK catches and wraps with its own LDAPException.

All of this is happening inside Java's TLS processing code, and the LDAP SDK doesn't really have much more control over or insight into what's going on. Without debug information from earlier in the process, I can't really say what caused the failure. I also don't know why inserting a delay would change things. However, it does look like there had already been a couple of TLS sessions that had been successfully established. Given that there is a renegotiation in progress, maybe it's related to an attempt to reuse a session that's being destroyed or invalidated.

You mention that you're using a custom socket factory. That also raises some questions:
* Does that socket factory do anything unusual? Might it be invalidating sessions?
* Might there be a thread safety problem in that socket factory that you had been protected from by defaulting to not allowing concurrent socket factory use in unrecognized JVM implementations in earlier versions of the LDAP SDK? Does the problem still occur if you call LDAPConnectionOptions.setAllowConcurrentSocketFactoryUse(false)? Perhaps injecting the delay has a similar effect to reducing contention and avoids the thread safety problem.
* Do you see the problem if you take your socket factory out of the picture?

It also sounds like it only happens in one specific environment. It would obviously be good to look at what might be different in that environment, and especially related to the server's TLS configuration, whether you have any networking equipment in the picture that might do weird things (especially something that might involve TLS, like a load balancer that acts as an SSL endpoint).

All of this is just speculation based on a few pieces of information, but it's really about all there is to go on right now.

**Comment by Fourfour06** [comment]
> I would have expected more debug output.

Problem is that the output is 8600+ lines for a one minute time-period, which is quite big.
Plus I need to double-check first if it doesn't contain any sensible data before putting it publicly here.

To answer you:

> Does that socket factory do anything unusual? Might it be invalidating sessions?

I haven't personally worked on this custom socket factory code, and from what I know it's old-legacy code that no one ever changed since it always worked until now. But yes I found this at the very end of createSocket method implementation right before returning the created socket itself (I'm not the comment's author):
 
```
// all session are invalidated directly to not be reused. But as javadoc told :
// any existing connection using this session can continue to use the session until the connection is closed.
( ( (SSLSocket) socket ).getSession() ).invalidate();
```

> Might there be a thread safety problem in that socket factory that you had been protected from by defaulting to not allowing concurrent socket factory use in unrecognized JVM implementations in earlier versions of the LDAP SDK?

There might ... There's a lot of singleton and thread-local variable usage there that I need to understand deeper. Anyway, should this socket-factory be thread-safe? Before using UnboundId, we use to have JNDI which worked with the very same socket-factory. Do you have any knowledge whether JNDI use or not multi-threaded socket creation?

> Does the problem still occur if you call LDAPConnectionOptions.setAllowConcurrentSocketFactoryUse(false)? Perhaps injecting the delay has a similar effect to reducing contention and avoids the thread safety problem.

I'll give a try and tell you the result, but I think it's going to work as it will pretty-much result in going back to 4.0.6 behavior which defaulted to single-threaded socket factory use because Amazon wasn't recognized as a "known" JVM vendor.

> Do you see the problem if you take your socket factory out of the picture?

Hard to say because our custom socket factory does a lot of things that couldn't really be replaced easily with a "default" one.

For your information I'll be out-of-the-office during the next week, but I'll go back to that topic the week after.

Thanks anyway for your current analysis.
My "best" guess would be an unsafe-thread operation performed by our socket-factory.
I'll have a look and tell you if I find something.

**Comment by dirmgr** [comment]
Given that the custom socket factory tries to invalidate the session immediately after creating the connection, then I'm guessing that it is a thread safety issue. In particular, if you're trying to establish two connections concurrently, then it's possible that they could both end up using the same SSL session, but the second one won't have completed negotiation by the time the session is invalidated, which could cause the failure that you're seeing.

I don't think that Java provides any way to explicitly prevent reusing a session, so if you don't want to permit reuse, then you're stuck with hacks like invalidating the session. But if that can't be done safely, then you'll have to use locking in the socket factory, at least around the portion of the code between creating the socket and invalidating the session. That should ensure that no two connections end up sharing the same session. Of course, if that's basically all that your socket factory does, then it might be easier to just use the `LDAPConnectionOptions.setAllowConcurrentSocketFactoryUse` method to force it to be single-threaded.

If you're okay with only a limited amount of session sharing, then you could consider using the [`SSLSessionContext.setSessionTimeout`](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLSessionContext.html#setSessionTimeout-int-) method. You could configure it so that sessions may only be cached for a maximum of one second, so that connections created within the same second from the same client may share the same session, but connections created more than a second apart will use different sessions.

Do you know why the socket factory tries to prevent session sharing? The main reason I can think of off the top of my head is that you're doing performance testing involving creating lots of TLS-encrypted connections and you want to force a complete negotiation each time to simulate the load you'd encounter from lots of different clients. If you're not doing something like that, then I would think that you'd want to leverage session sharing as much as possible because it can dramatically improve performance when establishing multiple TLS-encrypted connections from the same client system.

**Comment by Fourfour06** [comment]
Ok, so fortunately I'm able to provide builds to our test environment and run the failing steps in order to find fix candidates. Here are the things that I have been trying so far:

- Lock the portion of code creating the socket/invalidating the session
- Force setAllowConcurrentSocketFactoryUse to false (but was already false by default in our case)
- Force setUseSynchronousMode to true
- Force set session timeout to 1000ms
- Remove the code invalidating the session before returning the new socket in createSocket method of our own SocketFactory (the one quoted in my previous comment)

For the latter, here is the explanation I found from the developper who wrote it 16 years ago (yes, you read correctly). The original issue was _LDAP replication fails due to failing TLS session resume in slapd_. For better understanding, _engines_ are appliances hosting the LDAP server, and _management_ is our Java-based server-application communicating with engines and creating LDAP connections to them:

> Based observations in our tests, the problem with 2.2.3 engine is a bug in
> openssl's session initialisation that makes session re-use to fail. While
> running slapd with higher debug level, it says it cannot initialise the context
> of the later connection (with TLS-type HELLO and session ID from previous
> successful connection).
> 
> See page: http://www.openldap.org/lists/openldap-software/200209/msg00464.html
> 
> It says that openssl have this bug from version 0.9.6g. The engine 2.2.1 used
> openssl v. 0.9.6c, but security patched openssl (in 2.2.2 engine) is 0.9.7b.
> There would be a patch available for openssl.
> 
> As a workaround for this, session re-using should be disabled in management side.
> 
> Previous fix on management side was not working, it seems that ssl layer
> behavior is not the same on developpment environnement and on real build.
> Here i provide a new fix that invalidates connections in LDAPS to engine
> conenctions.


None of the attempts above worked so far, and our test is still failing because of error code 81 which I still don't manage to reproduce in my own environment (I'm having error code 91 but it seems to be related to our LDAP server having multiple valid certificates and not using the correct one. A reboot fixes this problem, but not the error code 81 faced by our test environment).

I'll give a try with a Oracle JDK see if behavior are different as I seem to have noticed differences in SocketFactory code. But for now, I don't see any other leads.

**Comment by dirmgr** [comment]
To clarify, you're saying that you tried all of the things in the bulleted list above and are still consistently seeing the problem in your test environment?

Have you tried testing without your custom socket factory to see if the problem goes away when not using it? If the reason that you're invalidating sessions is related to a 16-year-old problem that probably isn't a problem anymore with modern software versions, then maybe you don't need the custom socket factory.

The only other thing I can think of off the top of my head would be to check out and build the LDAP SDK for yourself, but after commenting out the line that starts the handshake in com.unboundid.ldap.sdk.ConnecThread (the change made in commit 9a19a281039942e79cc994d14923f3cedd6106b0 as described above). That would help us figure out if the problem somehow stems from kicking off the handshake as soon as we establish the connection rather than waiting for the first attempt to communicate on the connection.

I suppose you could also try adding code that catches the exception from catch+bind and tries again on a newly created connection. That clearly wouldn't be an actual solution to the problem, but it might help figure out whether this is a race condition or something else.

**Comment by Fourfour06** [comment]
So after multiple tries, including getting rid of the previous socket factory and replacing it with a more standard one, the problem went away.

Our custom socket factory is actually doing a lot of things including double-checking SSL certificates which sometimes results in performing additional handshakes/connections sometimes done by different threads, which doesn't seem to be well compatible with latest 4.0.11 version (maybe something changed at this particular level on your side between 4.0.6 and 4.0.11?).

Anyway, the problem is clearly not on your side but rather on our way to deal with the things our custom socket factory has to do, so let's close this ticket.

Thanks for you time and your enlightening suggestions and analysis which helped us a lot during our investigation.

**Comment by dirmgr** [comment]
As I mentioned above, the only thing I can think of that might have changed in the LDAP SDK is that we start the handshake immediately on establishing a TLS-based connection instead of waiting until the first attempt to communicate on the connection. That shouldn't cause a problem, but it might exacerbate an existing race condition.

We also did recently enable support for TLSv1.3 if the JVM offers it, but that shouldn't come into play unless you're running Java 11 and it sounds like you're on Java 8.
