### ISSUE TITLE
How to Log SearchRequests in human readable format?

### ISSUE THREAD

**Issue by regenrek** [pingidentity/ldapsdk#79]
Hi

I've wondering how I can log Search Requests which I receive from the client easily? 

What I've done so far:

```
            System.setProperty("com.unboundid.ldap.sdk.debug.enabled","true");
            System.setProperty("com.unboundid.ldap.sdk.debug.level","DEBUG");
            System.setProperty("com.unboundid.ldap.sdk.debug.type","LDAP");
```

No output. Only this works

```
            System.setProperty("com.unboundid.ldap.sdk.debug.enabled","true");
            System.setProperty("com.unboundid.ldap.sdk.debug.level","ALL");
            System.setProperty("com.unboundid.ldap.sdk.debug.type","ASN1");
```

or this works too:

```
        com.unboundid.util.Debug.setEnabled(true);
```

I would prefer to log bind/search/... whatever request in the log file in a human
readable forma like:

```
 Date / Time / Level / Class ... SearchRequest  
```

I also was reading in to listeners like the `LDAPListenerRequestHandler` and extend
this class with my custom code. Do I need this to solve my custom log output or
is there an easier method?

**Comment by dirmgr** [comment]
It sounds like you're accepting connections from LDAP clients using an LDAP listener (or the in-memory directory server, which uses the LDAP listener framework behind the scenes) rather than acting as a client. In that case, the LDAP SDK already provides an [AccessLogRequestHandler](https://docs.ldap.com/ldap-sdk/docs/javadoc/index.html?com/unboundid/ldap/listener/AccessLogRequestHandler.html) that can accomplish this for you. You provide it with a java.util.logging.Handler to which the log messages will be sent, and a com.unboundid.ldap.listener.LDAPListenerRequestHandler that will be used to actually process the requests. When the access log request handler receives a request, it logs information about that request and then passes it on to the wrapped request handler to be processed. When that wrapped request handler returns a result, the access log request handler logs information about that result before returning it to the client.

The output that this access logger generates looks like the following:

```
[18/Feb/2020:09:42:18 -0600] CONNECT conn=1 from="127.0.0.1:35794" to="127.0.0.1:1389"
[18/Feb/2020:09:42:18 -0600] SEARCH REQUEST conn=1 op=0 msgID=1 base="dc=example,dc=com" scope=2 filter="(uid=jdoe)" attrs="ALL"
[18/Feb/2020:09:42:18 -0600] SEARCH RESULT conn=1 op=0 msgID=1 resultCode=0 etime=1.569 entriesReturned=1
[18/Feb/2020:09:42:18 -0600] UNBIND REQUEST conn=1 op=1 msgID=2
[18/Feb/2020:09:42:18 -0600] DISCONNECT conn=1
```

If you're using the in-memory directory server, then this is easy to do just by calling the InMemoryDirectoryServerConfig.setAccessLogHandler method to provide it with the Java logging handler. If you're using the LDAP listener framework outside of the in-memory directory server, then you can look at the [InMemoryDirectoryServer constructor](https://github.com/pingidentity/ldapsdk/blob/master/src/com/unboundid/ldap/listener/InMemoryDirectoryServer.java#L281) for an example that demonstrates this.

Note that the LDAP SDK also offers an [LDAPDebuggerRequestHandler](https://docs.ldap.com/ldap-sdk/docs/javadoc/index.html?com/unboundid/ldap/listener/LDAPDebuggerRequestHandler.html) that provides even more verbose output about the requests that it receives. This is useful in cases where the regular access logger doesn't provide enough information about the request or response. The LDAP debugger request handler uses more verbose output, like:

```
CONNECT conn=1 from="127.0.0.1:35818" to="127.0.0.1:1389"

conn=1 from="127.0.0.1:35818" to="127.0.0.1:1389"
LDAP Message:
     Message ID:  1
     Search Request Protocol Op:
          Base DN:  dc=example,dc=com
          Scope:  SUB
          Dereference Policy:  NEVER
          Size Limit:  0
          Time Limit:  0
          Types Only:  false
          Filter:  (uid=jdoe)

conn=1 from="127.0.0.1:35818" to="127.0.0.1:1389"
LDAP Message:
     Message ID:  1
     Search Result Entry Protocol Op:
          dn: uid=jdoe,ou=People,dc=example,dc=com
          objectClass: top
          objectClass: person
          objectClass: organizationalPerson
          objectClass: inetOrgPerson
          uid: jdoe
          givenName: John
          sn: Doe
          cn: John Doe
          entryDN: uid=jdoe,ou=people,dc=example,dc=com
          entryUUID: 18d06e87-d9de-4630-b66c-38130f1e7fb4
          subschemaSubentry: cn=schema
          creatorsName: 
          createTimestamp: 20200218154515.412Z
          modifiersName: 
          modifyTimestamp: 20200218154515.412Z

conn=1 from="127.0.0.1:35818" to="127.0.0.1:1389"
LDAP Message:
     Message ID:  1
     Search Result Done Protocol Op:
          Result Code:  0 (success)

conn=1 from="127.0.0.1:35818" to="127.0.0.1:1389"
LDAP Message:
     Message ID:  2
     Unbind Request Protocol Op:

DISCONNECT conn=1 from="127.0.0.1:35818" to="127.0.0.1:1389"
```

Further, the next release of the LDAP SDK (or you can get it now if you check out and build the SDK for yourself) will include a JSON-formatted access logger that writes log messages as JSON objects so that they can be more easily parsed. That output looks like:

```
{ "timestamp":"2020-02-18T15:45:19.613Z", "message-type":"connect", "connection-id":1, "from-address":"127.0.0.1", "from-port":35818, "to-address":"127.0.0.1", "to-port":1389 }
{ "timestamp":"2020-02-18T15:45:19.635Z", "message-type":"request", "operation-type":"search", "connection-id":1, "operation-id":0, "message-id":1, "base":"dc=example,dc=com", "scope":2, "filter":"(uid=jdoe)", "requested-attributes":[ ] }
{ "timestamp":"2020-02-18T15:45:19.636Z", "message-type":"response", "operation-type":"search", "connection-id":1, "operation-id":0, "message-id":1, "result-code-value":0, "result-code-name":"success", "processing-time-millis":1.360, "entries-returned":1 }
{ "timestamp":"2020-02-18T15:45:19.651Z", "message-type":"request", "operation-type":"unbind", "connection-id":1, "operation-id":1, "message-id":2 }
{ "timestamp":"2020-02-18T15:45:19.651Z", "message-type":"disconnect", "connection-id":1 }
```

**Comment by regenrek** [comment]
Hi,
oh didn't expect this detailled explanation. 

>If you're using the in-memory directory server, then this is easy to do just by calling the InMemoryDirectoryServerConfig.setAccessLogHandler method to provide it with the Java logging handler. 

Yep I'm using this approach. Is it possible to add a slf4j log handler to it? Or do I missunderstand here something?

This is how I call the logger:

```java
    private static final Logger logger = LoggerFactory.getLogger(LDAP.class);
        InMemoryDirectoryServerConfig config = new InMemoryDirectoryServerConfig(someConfig);
        config.setAccessLogHandler();
//        config.setLDAPDebugLogHandler(new LDAPDebugLogHandler());
```

**Comment by dirmgr** [comment]
The LDAP SDK does not (and will not) have any third-party dependencies, so it won’t provide any direct integration with slf4j. However, although I’m not familiar with that framework, I assume that it should be a very simple matter to create a simple bridge that implements provides a Java logging handler that just calls the corresponding methods in slf4j. I wouldn’t be at all surprised if something like that already exists.

**Comment by regenrek** [comment]
@dirmgr thank you for your response. Indeed you we're right. I post a solution for anyone who comes here. 

```java

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.logging.LogRecord;
import java.util.logging.Handler;

public class AccessLogger extends Handler {

    private static final Logger log = LoggerFactory.getLogger("access");

    @Override
    public void publish(LogRecord record) {
        log.info(record.getMessage(),record.getThrown());
    }

    @Override
    public void flush() {
    }

    @Override
    public void close() throws SecurityException {
    }
}
```

**Comment by regenrek** [comment]
Hi @dirmgr ,

how can I do the opposite of my previous case. What I mean is how can I log the request/response from the client side? 

What I've done so far is to create a separate LDAPListener with the `AccessLogRequestHandler` but there is not output to see yet. I want to Log for example a search Request with its parameters.

```java
        try {
            searchResult = connection.search(request);
        }
        catch (LDAPSearchException lse) {
      }  
```

should output something similiar which Debug.setEnabled does

``` 
SEARCH REQUEST: { "timestamp":"2020-03-04T14:17:41.978Z", "debug-type":"ldap", "level":"INFO", "thread-id":1, "thread-name":"main", "connection-id":0, "connected-to-address":"192.168.1.1", "connected-to-port":1389, "socket-timeout-millis":300000, "message-id":1, "sending-ldap-request":"SearchRequest(baseDN='dc=example', scope=SUB, deref=NEVER, sizeLimit=0, timeLimit=0, filter='(&(hero=Spiderman))', attrs={title, profession})", "ldap-sdk-version":"5.0.0", "ldap-sdk-revision":"..." }
SEARCH ENTRIES: { "timestamp":"2020-03-04T14:17:43.147Z", "debug-type":"ldap", "level":"INFO", "thread-id":34, "thread-name":"Connection reader for connection 0 to 192.168.1.1:1389", "connection-id":0, "connected-to-address":"192.168.1.1", "connected-to-port":1389, "read-ldap-result":"SearchResultEntry(dn='dc=example', messageID=1, attributes={Attribute(name=title, base64Values={'....'}), Attribute(name=title, values={'Spiderman'}), Attribute(name=profession, values={'Sticky'})}, controls={})", "ldap-sdk-version":"5.0.0", "ldap-sdk-revision":"..." }
SEARCH RESULT: { "timestamp":"2020-03-04T14:17:43.193Z", "debug-type":"ldap", "level":"INFO", "thread-id":34, "thread-name":"Connection reader for connection 0 to 192.168.1.1:1389", "connection-id":0, "connected-to-address":"192.168.42.1", "connected-to-port":389, "read-ldap-result":"SearchResult(resultCode=0 (success), messageID=1)", "ldap-sdk-version":"5.0.0", "ldap-sdk-revision":"..." }
```

**Comment by dirmgr** [comment]
With the current version of the LDAP SDK, the debug logger is about the only way to get that. But I've just committed a change that adds an LDAPConnectionLogger API that can be used to log information about successful and failed connection attempts, operation requests and results, and disconnects. There's a JSONLDAPConnectionLogger implementation that formats log messages as JSON objects, but you can write your own logger implementation if you want a different format.

**Comment by regenrek** [comment]
Thank you thats awesome!
