### ISSUE TITLE
[Embedded LDAP] How to delay an operation?

### ISSUE THREAD

**Issue by regenrek** [pingidentity/ldapsdk#81]
Hi

for some tests I would like to delay the response for a search request to a specific
amount of ms/seconds. Is this somehow possible?

Like Request -> wait 2 sec -> Send Response.

The reason I need this is to test an `abandon` request which I send after the
search Request. Perhaps there is a better way but this was something we came up with
to test the cancel of an request.

Regards

**Comment by dirmgr** [comment]
You can use the `InMemoryDirectoryServer.setProcessingDelayMillis` method to cause the server to inject a specified delay before it processes each request. This can be changed with the server online so that only certain operations are affected. It doesn't look like the in-memory-directory-server tool offers an argument that can be used to configure a delay from the command line in case that's what you're using.

Unfortunately, this won't work for what you want because the in-memory directory server doesn't currently support abandon operations. It will accept the request, but it will just ignore it without doing anything. For simplicity, the server uses a dedicated thread per connection (rather than a more complicated structure like a work queue with threads pulling from it), so once it starts processing a client request, it won't see any other requests from the same client until it's done working on the current request. This means that it's not possible for it to handle abandon operations because it won't see the abandon request until it's done processing the operation that it's supposed to abandon. It also means that if you send multiple requests over the same connection asynchronously, they'll be processed in sequence rather than concurrently.

**Comment by regenrek** [comment]
Hi @dirmgr thank you for the insights. That was everything I needed.
