### ISSUE TITLE
Possible to disable Response from a client request sent?

### ISSUE THREAD

**Issue by regenrek** [pingidentity/ldapsdk#82]
Hi,

can we configure the inmemory server in some sort to ignore a Search Response from a request sent from a client? 

For example 

```
Client: Send Bind Request -> Ok -> Log
Client: Send Search Request -> OK -> Log
Client: Search Response -> ignore (no logging) -> no data sent back / or deny 
Client: Send Abandon Request -> Ignored (due Inmemory unsupported) -> Log
close
``` 

Reason behind this is to show that a abandon request stops the Search Response accordingly

Regards

**Comment by dirmgr** [comment]
The in-memory directory server doesn't have the ability to do that directly, but it looks like it should be possible to do with the more generic LDAPListener framework. Basically, you would need to create an LDAPListenerRequestHandler that is configured with an InMemoryRequestHandler. Your custom request handler can look at each request that it receives and decide how to handle it. If it's one that should be processed, then it would call the corresponding method in the in-memory request handler and return the result that it provides. Alternately, you could decide to return a custom result from your own request handler, or even return null to indicate that no response should be returned.

The LDAPListenerRequestHandler API wasn't really designed with this in mind, but it looks like it should work, and returning null from a method like processSearchRequest should cause no response to be returned.

**Comment by regenrek** [comment]
Hi @dirmgr 

I've ended up with some `CustomProxyRequestHandler` (LDAPListenerRequestHandler) where I send some custom result instead of the `SearchResultDoneOp`. Somehow I couldn't manage to return null or an EmptyResponse. Everytime I tried some other response than `SearchResultDoneProtocolOp` it stopped with an exception on client side. Somehow the  SDK awaits the `SearchResultDoneProtocolOp` and I couldn't change the `ResultCode` (like `ResultCode.CANCELED`)... this isn't fully clear to me but in overall it works now.

```java  
        SearchResultCancelProtocolOp searchResultCancelProtocolOp = new SearchResultCancelProtocolOp(((LDAPResult)searchResult).getResultCode().intValue(), ((LDAPResult)searchResult).getMatchedDN(), ((LDAPResult)searchResult).getDiagnosticMessage(), Arrays.asList(((LDAPResult)searchResult).getReferralURLs()));
        return new LDAPMessage(messageID, searchResultCancelProtocolOp);
```

And a CustomLogRequestHandler where I modified the `processSearchRequest` method to avoid the output in the logs for this scenario.

```
            final LDAPMessage responseMessage = requestHandler.processSearchRequest(
                messageID, request, controls);
            
   // not output logging

            return responseMessage;
```

Thanks!

**Comment by dirmgr** [comment]
If you successfully abandon an operation, then the directory server won't send the final response for that operation. If a client is waiting for the response, then it may continue to wait forever, or at least until it gives up (e.g., because of a client-side timeout) or something else happens to interrupt it (e.g., the server closes the connection to the client).

This is a significant downside of using the LDAP abandon operation, and in general, you should only send an abandon request if you know that you're not going to wait for the response anymore. Further, the abandon request itself doesn't have a response, so you don't know whether the operation was abandoned or not.

If you want to interrupt a request from one thread while another thread continues to wait for a response to that original request, then a better choice would be to use the LDAP [cancel extended operation](https://docs.ldap.com/ldap-sdk/docs/javadoc/index.html?com/unboundid/ldap/sdk/extensions/CancelExtendedRequest.html) as described in [RFC 3909](https://docs.ldap.com/specs/rfc3909.txt). When using the cancel operation, the cancel request will receive a result indicating whether the cancel was successful or not, and if the operation was canceled, then the server will return a response to the original client with a "canceled" result code (integer value 118).

Note that the in-memory directory server doesn't include support for the cancel operation because of the synchronous nature of its processing. It would be possible to create an [InMemoryExtendedOperationHandler](https://docs.ldap.com/ldap-sdk/docs/javadoc/index.html?com/unboundid/ldap/listener/InMemoryExtendedOperationHandler.html) that provides support for it, but the server wouldn't ever see that request until it finishes the request it's already working on, so there really wouldn't be any benefit.
