### ISSUE TITLE
Retrieving ObjectGUID 

### ISSUE THREAD

**Issue by djavia3** [pingidentity/ldapsdk#91]
Is there a helper method to retrieve ObjectGUID as a string? I'm trying to serialize/deserialize objectGUID to a string so that I can use it in to search by that attribute.

**Comment by dirmgr** [comment]
No, the LDAP SDK doesn't provide any helper method that is specific to the objectGUID attribute. However, if its value is binary and you just want to use that value directly, then you shouldn't need a helper method. You should just be able to create a filter directly using that binary value without any string conversion. The LDAP SDK will take care of any necessary escaping. For example:

    final byte[] objectGUIDBytes = entry.getAttributeValueBytes("objectGUID");
    final Filter objectGUIDFilter =
         Filter.createEqualityFilter("objectGUID", objectGUIDBytes);

I'm really not familiar with all of the unusual things that Microsoft does in Active Directory, but as far as I can tell from some quick searching, the above should work if you've already got the binary representation. Converting between the binary and string representations does look to be a little more complex and doesn't seem to make a whole lot of sense. As far as I can tell, if you have the string representation of the UUID, you need to convert the first four bytes from Big Endian to Little Endian, the next two bytes from Big Endian to Little Endian, the two bytes after that from Big Endian to Little Endian, and then leave the remaining eight bytes as Big Endian. I'm not going to even bother to take a guess as to why that's the case, but hopefully you can just work with the value in binary form so that no conversion is necessary.
